#!/bin/bash

USER= #
PASS= #
COOKIE=.optipos_dicts.cookie
URL1="http://optiposlodz-vip.centertel.pl:7701/"
URL2="https://optipos.centertel.pl/"
DATE=$(date +%s)000
OUTPUT=.optipos_dict.txt
TIMEOUT=120

DICTS=(ACCTYPE_REASON ACCTYPE_SRVPKG AGREEMENT AGREE_AGR_STATE AGREE_CHANNEL AGREE_CONTENT AGREE_DEPENDENCY BANK_BRANCH BORNEO_ACCOUNT_SERVICE BORNEO_ACCOUNT_SERVICE_PARAMS BORNEO_BPK_RANGE BORNEO_BPK_VALUE BORNEO_OFFER_RELATION BORNEO_SERVICE_DICT_PARAMS BORNEO_SRV_PACKAGE BUDGET CHANNEL COMBO COMMITMENT COMMITMENT_ONE COMMITMENT_TEXAS COMMUNE COMPLEX_OPTIONS COUNTY CRM_CASE_DEF CRM_CASE_NOT_AVAIL CRM_QUESTION CRM_QUESTIONNAIRE_CALC CRM_QUESTION_ANSWER DEVICE_TYPE DOCUMENT_CHANNEL DOCUMENT_CONTENT DOCUMENT_PARAM FAULT FAULT_MESSAGE FNP_HOLIDAY FUNCTION FUNCTION_LEVEL FUNCTION_ROLE IDM_CHANNEL IFS_TERMINALS INSTALMENT_PLAN LNU_REGULATIONS MARKFIELD MARKFIELD_COMBO MUFLON_INFO NBTL_PRINT_TEXT OFFER_PRICE_LIST OFFLINE_PARAMETERS ONE_PROM_DECL_PAYMENT ONE_PROM_PAYMENT ONE_PROM_PERIOD ONE_PROM_PHONESET ONE_PROM_RP OPS_BONUS OPTGRP_OPTION OPTGRP_OPTION_CONF OPTGRP_PURPOSE OPTION OPTION_BONUS_DISCOUNT OPTION_BONUS_MARKER OPTION_BONUS_MARKER_E OPTION_CONDITION OPTION_DEFINITION OPTION_ELEMENTS OPTION_GROUP OPTION_GROUP_LNU_COUNT_DEP OPTION_ORDER OPTION_ORDER_EXCLUSION OPTION_PARAM OPTION_PARAM_COMBO OPTION_PRICE OPTION_REGULATIONS OPTION_RELATIONS_ZERO PHONEGRP_PHONESET PHONESET PHONESET_GROUP_REF_DEL_ME PHONESET_GRP PHONESET_IFS_ITEM PHONESET_MARKET_PRICE PHONESET_PRINT POSSIBLE_MIGRATIONS POS_RATEPLAN POS_TERMINAL_LIMITS PRIMARY_SERVICES PRINT_AGREE_STATE PRINT_VIEW PRINT_VIEW_DATA PRODUCER PROMOTION PROMOTION_ALL PROMOTION_GROUP PROMOTION_PERIOD PROMOTION_PHONESET PROMOTION_PRINT PROMOTION_RP PROMOTION_SERVICE PROM_CHANNEL PROM_CONFIGURATION PROM_DEPENDENCY PROM_PARAM PROM_PERIOD PROM_RATEPLAN PROM_RELATION PROM_TOTAL_COM PRPS_CHURN_LIST PV_DEPENDENCY RATEPLAN_GROUP RATEPLAN_IN_MAP REASON_CONTRACT REASON_CUSTTYPE REPAIR_SHOP ROLE SERVICE SERVICE_GROUP SERVICE_REGULATIONS SERVICE_RELATIONS_ZERO SMPAD_TARIFF SM_CUSTOMER_DTO SOV_REP_INFO_POS SRVGRP_SERVICE SRV_GROUP SRV_PARAM SRV_PARAM_COMBO SRV_PRIMARY_SERVICE SRV_RELATION SSLINK_DEP TERMINAL_RELATION TEX_PROM_PERIOD TEX_PROM_PHONESET TEX_PROM_SRVGRP TRANS_LINKS UPSELLER_OPTIONS VOUCHER_AND_TERMINAL_OPTIONS)
DICTS_SIZE=${#DICTS[@]}

echo > $OUTPUT
curl -s -k -X POST -d login=$USER -d password=$PASS -d "domain=OTSA&action=submit" -b $COOKIE -c $COOKIE "https://voptisso-vip.centertel.pl/webSSO/auth/simple/verify.do" -o /dev/null
curl -s -k -X GET -b $COOKIE -c $COOKIE $URL1"optipos/otsa/index.do" -o /dev/null

for DICT in ${DICTS[*]}; do
        REQUEST1=$URL1"optipos/otsa/GetJsonDict?dict="$DICT"&changed="$DATE
        REQUEST2=$URL2"optipos/otsa/GetJsonDict?dict="$DICT"&changed="$DATE
        FILE1="."$DICT".optiposlodz-vip.centertel.pl.json"
        FILE2="."$DICT".optipos.centertel.pl.json"
        curl -m $TIMEOUT -s -X GET -b $COOKIE -c $COOKIE $REQUEST1 -o $FILE1
        /opt/rsw_maint/jdk/bin/java -jar /opt/rsw_maint/json-schema-validator-2.2.6-lib.jar --syntax $FILE1 >> $OUTPUT 2>&1
	echo -e "\n" >> $OUTPUT
        curl -k -m $TIMEOUT -s -X GET -b $COOKIE -c $COOKIE $REQUEST2 -o $FILE2".gz"
	gunzip -f $FILE2".gz"
        /opt/rsw_maint/jdk/bin/java -jar /opt/rsw_maint/json-schema-validator-2.2.6-lib.jar --syntax $FILE2 >> $OUTPUT 2>&1
	echo -e "\n" >> $OUTPUT
        rm -f $FILE1 $FILE2
done

DICTS_SIZE2=$(($DICTS_SIZE * 2))
SUCCESSES=$(grep -c "SUCCESS" $OUTPUT)
SUBJECT="OPTIPOS DICTS "$SUCCESSES"/"$DICTS_SIZE2" OK"
if (( $SUCCESSES != $DICTS_SIZE2 )) ; then
	FUCKUPS=$(($DICTS_SIZE2-$SUCCESSES))
	SUBJECT="!!! "$SUBJECT" "$FUCKUPS"/"$DICTS_SIZE2" NOK !!!"
else
	SUBJECT=$SUBJECT" :)"
fi

MESSAGE=$(< $OUTPUT)
echo "$MESSAGE" | mail -s "$SUBJECT" optipossupport_gu2@bluesoft.com

rm -f $COOKIE $OUTPUT

